### ISSUE TITLE
Is there any literature I can follow?

### ISSUE THREAD

**Issue by shuaiwang88** [Valdecy/Metaheuristic-Local_Search-Tabu_Search#1]
Hi! 
Thank you so much for the detailed code.
Can you provide any reading material like literature to implement the code?

**Comment by Valdecy** [comment]
Sorry I didn't notice this issue until now.  Here is a good article: https://ascelibrary.org/doi/pdf/10.1061/(ASCE)TE.1943-5436.0000447?casa_token=uJWkjZF2h8wAAAAA%3ATbYAbZvKl2wqaqK9b-pgc6JzzJynkjfwCfK_uIhw2dqELLIFBi9v3ck_nTEWzhsKUQWQSkmtQfpMsg&
